name: Build and Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-release*
          path: target/${{ matrix.target }}/release
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/x86_64-pc-windows-gnu/release/*
            target/x86_64-unknown-linux-musl/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}