name: Build and Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Prepare
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: debug
        run: ls -l target/${{ matrix.target }}/release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: target/${{ matrix.target }}/release/traffic_middleware${{ matrix.target == 'x86_64-pc-windows-gnu' && '.exe' || '' }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            traffic_middleware/*
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
